buildscript {
    ext.kotlin_version = '2.0.10'
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.5.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

// plugins block must come right after buildscript (if present)
plugins {
    id 'com.android.library' // Use 'com.android.library' for plugins, not 'com.android.application'
    id 'kotlin-android'
}

group 'me.arsam.sms_retriever'
version '1.0.0'

android {
    compileSdk 34
    namespace 'me.arsam.sms_retriever'
    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }
    defaultConfig {
        minSdkVersion 28
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }
    lintOptions {
        disable 'InvalidPackage'
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.google.android.gms:play-services-auth:19.0.0'
    implementation 'com.google.android.gms:play-services-auth-api-phone:18.1.0'
}